export const settings = {
  SECTOR_SIZE: 50,
  VELOCITY: 2,
  MAX_BOIDS: 1000,
  ADJUST_RATE: .008,
  REPEL_RATE: .015,
  DENSITY_DISTANCE: 30 / 2,  // Use the actual value: 15
  DENSITY_DISTANCE_SQUARED: 30 * 30,  // Use the actual value: 225
  MAX_FLOCKING_NEIGHBORS: 10,
  LIFESPAN: 200,
  BIRTHRATE: 4,
  GENE_BIAS_FACTOR: 5,
  COLOR_MUTATION: 20,
  MIN_LIFESPAN: 20
};